### ISSUE TITLE
Point cloud disappears after changing Container from Mesh to Texture 

### ISSUE THREAD

**Issue by ViktorVR** [ya7gisa0/Unity-Point-Cloud-VFX-Graph#1]
First of all, thank you so much for uploading this script and the video of the workshop. I'm trying to replicate your script but I'm running into the following problems:

I drag'n'dropped a sample point cloud into the canvas, then changed its container from Mesh to Texture. This caused the point cloud to disappear. Then I drag'n'dropped the Test>Particles VFX Graph onto the point cloud in the hierarchy. 

Then, I get only some particles spawning in a very small scale - the point cloud seemed to have disappeared.
<img width="1440" alt="Bildschirmfoto 2021-02-06 um 01 51 13" src="https://user-images.githubusercontent.com/63354731/107103402-ceee5c00-681d-11eb-8278-49a740f8226e.png">
<img width="1440" alt="Bildschirmfoto 2021-02-06 um 01 44 10" src="https://user-images.githubusercontent.com/63354731/107103326-8b93ed80-681d-11eb-9cea-5b95b63b4d0f.png">
<img width="1440" alt="Bildschirmfoto 2021-02-06 um 01 45 41" src="https://user-images.githubusercontent.com/63354731/107103327-8c2c8400-681d-11eb-8456-d19e72412f02.png">

**Comment by yumayanagisawa** [comment]
Hi, thanks for checking out the recording. After generating colour/position maps, you have to assign them to your VFX system. I guess I failed to explain that step clearly, but you can watch the particular section of the workshop: https://youtu.be/iqntF9NPqLw?t=1447

**Comment by yumayanagisawa** [comment]
@ViktorVR Any updates on this? I don't think the problem is not relevant to the project itself, so I will close this issue later probably...

**Comment by ViktorVR** [comment]
Thank you very much for getting back. I managed to make it work! Thank you so much for the script and the video!
